CREATE DATABASE db_basicaccounting;
USE db_basicaccounting;

CREATE TABLE tb_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    UNIQUE (Email),
    UNIQUE (Username)
);

CREATE TABLE tb_Pengajuan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    No_Hp VARCHAR(20) NOT NULL,
    Alamat TEXT NOT NULL,
    Kategori VARCHAR(100) NOT NULL,
    Lama_Waktu INT NOT NULL,
    tgl_dibuat DATETIME DEFAULT CURRENT_TIMESTAMP,
    tgl_diubah DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tb_input_layanan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    layanan VARCHAR(255) NOT NULL,
    deskripsi TEXT NOT NULL,
    lama_waktu INT NOT NULL,
    harga DECIMAL(10, 2) NOT NULL,
    tgl_dibuat DATETIME DEFAULT CURRENT_TIMESTAMP,
    tgl_diubah DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
